import { MetabaseEmbed } from "@/components/MetabaseEmbed";
import { Container } from "@/components/Container";
import { Highlight } from "@/components/Highlight";

// Dashboard public url (generated by metabase using "share">"public link")
// Make sure to use a https url to avoid mixed content errors in production
const TEST_DASHBOARD_PUBLIC_URL =
  "https://opi-metabase.services.d4g.fr/public/dashboard/a990e94e-caae-46b6-af09-6df2b600e8c2";

export default async function KeyMetricsPage() {
  const embedUrl = TEST_DASHBOARD_PUBLIC_URL;

  return (
    <main className="min-h-screen font-sans bg-background">
      <section aria-label="Hero" className="py-16 background-secondary">
        <Container>
          <div className="background-secondary rounded-3xl">
            <div className="relative block items-center px-12 pt-32 pb-16 overflow-hidden">
              <h1 className="text-hero text-center font-black text-muted leading-[1.1] mb-6">
                {"Les "}
                <Highlight bgClassName="bg-highlight-marker-hero">
                  {" chiffres "}
                </Highlight>
                {"derrière les posts"}
              </h1>
            </div>
          </div>
        </Container>
      </section>
      <MetabaseEmbed
        dashboardPublicUrl={embedUrl}
        title="Quelques chiffres"
        className="h-[var(--metabase-embed-height-hack-avoiding-double-scroll)]"
      />
    </main>
  );
}
