# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Account(BaseModel):
    """
    Account model.
    """ # noqa: E501
    account_extracted_at: datetime
    account_id: StrictStr
    social_network: StrictStr
    handle: Optional[StrictStr]
    description: StrictStr
    follower_count: StrictInt
    following_count: StrictInt
    post_count: StrictInt
    view_count: StrictInt
    like_count: StrictInt
    categories: List[StrictStr]
    __properties: ClassVar[List[str]] = ["account_extracted_at", "account_id", "social_network", "handle", "description", "follower_count", "following_count", "post_count", "view_count", "like_count", "categories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Account from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if handle (nullable) is None
        # and model_fields_set contains the field
        if self.handle is None and "handle" in self.model_fields_set:
            _dict['handle'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Account from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_extracted_at": obj.get("account_extracted_at"),
            "account_id": obj.get("account_id"),
            "social_network": obj.get("social_network"),
            "handle": obj.get("handle"),
            "description": obj.get("description"),
            "follower_count": obj.get("follower_count"),
            "following_count": obj.get("following_count"),
            "post_count": obj.get("post_count"),
            "view_count": obj.get("view_count"),
            "like_count": obj.get("like_count"),
            "categories": obj.get("categories")
        })
        return _obj


