# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExtractionTaskType(str, Enum):
    """
    Types of extraction tasks.
    """

    """
    allowed enum values
    """
    EXTRACT_MINUS_ACCOUNT = 'extract-account'
    EXTRACT_MINUS_POST_MINUS_LIST = 'extract-post-list'
    EXTRACT_MINUS_POST_MINUS_DETAILS = 'extract-post-details'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExtractionTaskType from a JSON string"""
        return cls(json.loads(json_str))


