# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from api_client.models.extraction_task_type import ExtractionTaskType
from api_client.models.social_network import SocialNetwork
from api_client.models.task_config1 import TaskConfig1
from typing import Optional, Set
from typing_extensions import Self

class ExtractionTaskResponse(BaseModel):
    """
    Extraction task response model.
    """ # noqa: E501
    task_uid: Optional[UUID] = None
    social_network: Optional[SocialNetwork] = None
    visible_at: Optional[datetime] = None
    type: Optional[ExtractionTaskType] = None
    task_config: Optional[TaskConfig1] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["task_uid", "social_network", "visible_at", "type", "task_config", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExtractionTaskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of task_config
        if self.task_config:
            _dict['task_config'] = self.task_config.to_dict()
        # set to None if task_uid (nullable) is None
        # and model_fields_set contains the field
        if self.task_uid is None and "task_uid" in self.model_fields_set:
            _dict['task_uid'] = None

        # set to None if social_network (nullable) is None
        # and model_fields_set contains the field
        if self.social_network is None and "social_network" in self.model_fields_set:
            _dict['social_network'] = None

        # set to None if visible_at (nullable) is None
        # and model_fields_set contains the field
        if self.visible_at is None and "visible_at" in self.model_fields_set:
            _dict['visible_at'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if task_config (nullable) is None
        # and model_fields_set contains the field
        if self.task_config is None and "task_config" in self.model_fields_set:
            _dict['task_config'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExtractionTaskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_uid": obj.get("task_uid"),
            "social_network": obj.get("social_network"),
            "visible_at": obj.get("visible_at"),
            "type": obj.get("type"),
            "task_config": TaskConfig1.from_dict(obj["task_config"]) if obj.get("task_config") is not None else None,
            "error": obj.get("error")
        })
        return _obj


