# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Post(BaseModel):
    """
    Post model.
    """ # noqa: E501
    post_extracted_at: datetime
    social_network: StrictStr
    account_id: StrictStr
    post_id: StrictStr
    post_url: StrictStr
    title: StrictStr
    description: StrictStr
    comment_count: StrictInt
    view_count: StrictInt
    repost_count: StrictInt
    like_count: StrictInt
    share_count: StrictInt
    categories: List[StrictStr]
    tags: List[StrictStr]
    sn_has_paid_placement: StrictBool
    sn_brand: StrictStr
    post_type: StrictStr
    text_content: StrictStr
    __properties: ClassVar[List[str]] = ["post_extracted_at", "social_network", "account_id", "post_id", "post_url", "title", "description", "comment_count", "view_count", "repost_count", "like_count", "share_count", "categories", "tags", "sn_has_paid_placement", "sn_brand", "post_type", "text_content"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Post from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Post from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "post_extracted_at": obj.get("post_extracted_at"),
            "social_network": obj.get("social_network"),
            "account_id": obj.get("account_id"),
            "post_id": obj.get("post_id"),
            "post_url": obj.get("post_url"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "comment_count": obj.get("comment_count"),
            "view_count": obj.get("view_count"),
            "repost_count": obj.get("repost_count"),
            "like_count": obj.get("like_count"),
            "share_count": obj.get("share_count"),
            "categories": obj.get("categories"),
            "tags": obj.get("tags"),
            "sn_has_paid_placement": obj.get("sn_has_paid_placement"),
            "sn_brand": obj.get("sn_brand"),
            "post_type": obj.get("post_type"),
            "text_content": obj.get("text_content")
        })
        return _obj


