# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SocialNetwork(str, Enum):
    """
    Available social networks.
    """

    """
    allowed enum values
    """
    YOUTUBE = 'youtube'
    TIKTOK = 'tiktok'
    INSTAGRAM = 'instagram'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SocialNetwork from a JSON string"""
        return cls(json.loads(json_str))


