# coding: utf-8

"""
    Observatoire pratique influence API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from api_client.models.extract_account_task_config import ExtractAccountTaskConfig
from api_client.models.extract_post_details_task_config import ExtractPostDetailsTaskConfig
from api_client.models.extract_post_list_task_config import ExtractPostListTaskConfig
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

TASKCONFIG1_ANY_OF_SCHEMAS = ["ExtractAccountTaskConfig", "ExtractPostDetailsTaskConfig", "ExtractPostListTaskConfig"]

class TaskConfig1(BaseModel):
    """
    TaskConfig1
    """

    # data type: ExtractPostDetailsTaskConfig
    anyof_schema_1_validator: Optional[ExtractPostDetailsTaskConfig] = None
    # data type: ExtractPostListTaskConfig
    anyof_schema_2_validator: Optional[ExtractPostListTaskConfig] = None
    # data type: ExtractAccountTaskConfig
    anyof_schema_3_validator: Optional[ExtractAccountTaskConfig] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ExtractAccountTaskConfig, ExtractPostDetailsTaskConfig, ExtractPostListTaskConfig]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ExtractAccountTaskConfig", "ExtractPostDetailsTaskConfig", "ExtractPostListTaskConfig" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        if v is None:
            return v

        instance = TaskConfig1.model_construct()
        error_messages = []
        # validate data type: ExtractPostDetailsTaskConfig
        if not isinstance(v, ExtractPostDetailsTaskConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExtractPostDetailsTaskConfig`")
        else:
            return v

        # validate data type: ExtractPostListTaskConfig
        if not isinstance(v, ExtractPostListTaskConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExtractPostListTaskConfig`")
        else:
            return v

        # validate data type: ExtractAccountTaskConfig
        if not isinstance(v, ExtractAccountTaskConfig):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExtractAccountTaskConfig`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in TaskConfig1 with anyOf schemas: ExtractAccountTaskConfig, ExtractPostDetailsTaskConfig, ExtractPostListTaskConfig. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        # anyof_schema_1_validator: Optional[ExtractPostDetailsTaskConfig] = None
        try:
            instance.actual_instance = ExtractPostDetailsTaskConfig.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ExtractPostListTaskConfig] = None
        try:
            instance.actual_instance = ExtractPostListTaskConfig.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ExtractAccountTaskConfig] = None
        try:
            instance.actual_instance = ExtractAccountTaskConfig.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TaskConfig1 with anyOf schemas: ExtractAccountTaskConfig, ExtractPostDetailsTaskConfig, ExtractPostListTaskConfig. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ExtractAccountTaskConfig, ExtractPostDetailsTaskConfig, ExtractPostListTaskConfig]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


